---
title: "December Goals"
author: "Megan Ewing"
date: "12-06-2023"
categories: goals
format: 
  html:
    toc: true
editor: visual
---

**Goals for December:**

## Finish Manila Clam RNA seq analysis

I was hoping to get this wrapped up last month but classes got the better of me. With no classes starting next week, I think I'll be able to get this issue closed semi-quickly.

## Project Stuff

-   Set a meeting with Steven to get a more clear direction for a project.

    -   I'm interested in looking at the Olympia Oysters and their sex changes so if we head in that direction:

-   Start reading current/recent papers on the topic (maybe skim 2, deep read 1, per week?)

-   Brainstorm a direction / project and start thinking about the specifics

    -   This is particularly important as next quarter I'll be taking Proposal Writing and want to get the most out of the course.

-   Would also just like to get a clearer idea of what expectations are and what "success" should look like for me now that the first quarter / major adjustment is kind of over with.

## Organizing my brain / reflection

I've been trying to play with different ways to manage class, work, and lab stuff in a way that doesn't cause any to suffer, and also doesn't disrupt my work life balance (which I try to follow the rule of thirds on: a third work, a third family/friend commitments, and a third myself). As is, I'm spending 20-25 hours a week on "grad school stuff", which is about what my target is. But there definitely seemed to be a tradeoff between class and lab stuff, where if I felt like I was making good progress on one, the other was kind of lagging. I'm hoping with having less class time next quarter will help, because the days/weeks in November that I made the most progress on the RNA seq analysis were days that I didn't have my workflow disrupted by class or didn't have any homework/class stuff to focus on. If not though, my friend told me about his work taking projects on in "sprints" where they do 1-2 weeks on one project, then 1-2 on a different project, and go back and forth like that. I also remember Aspen mentioning that she focuses the first half of her week on TA duties, with the latter half on Lab/Project stuff. [So one goal I have for December (and January once classes start again) is to implement on of these strategies of time management]{.underline}, so I don't feel like I'm trying to juggle too many things at once, and can spend dedicated time on one thing at a time.
