---
title: "December Daily Posts"
author: "Megan Ewing"
date: "12-05-2023"
categories: daily
format: 
  html:
    toc: true
editor: visual
---

**Daily Notebook Updates for December**

## Dec. 5 - Final Prep / Quarter Wrap Up

This week I've put a pause on lab stuff to focus on wrapping up any assignments for the quarter and studying for the final in qsci. Goals for the week:

-   study for qsci

-   finish any remaining assignments

-   read chapters for lab meeting

-   get December goals posted

## Dec. 6 - Studying

Had my last class for fish552/3. Only have 1 assignment left for that which I should be wrapped up with by Friday night.

Currently compiling notes for qsci and reviewing old story assignments and labs. Tomorrow I'll take the practice midterm and then review any remaining topics from there.

## Dec. 12 - Kallisto

Had a work (non school) event this morning/afternoon. Afterwards I got back on the rnaseq workflow and unzipped the reference genome file. Ran the code to create the index file (currently still running). If that finishes in time then I'll run the kallisto chunks so they are ready for tomorrow to work on next steps during hack week.

## Dec. 13 - Hackweek and Kallisto

Woot woot finally moved through Kallisto and got a good and proper matrix. Now onto DESeq2. Got the volcano plot and am currently working on the heatmap. If I can get those done early tomorrow morning then it will be just blasting all day tomorrow: the manila clam rna seq data and the top marker genes for the oyster/geoduck files.

Today I also started hunting for papers to prep for the potential of working on an olympia oyster related project. Quickly realized I have pretty substantial knowledge gaps in oyster biology/physiology as a whole so starting a bit broader than expected, but at least have a bit of direction to head towards.

## Dec. 14 - Hackweek, DESeq2, Blast/Annotations, Meeting w Steven

Worked on DESeq2, got a .tab of differentially expressed genes and associated stats. Currently running blastx to get to annotation.

Also, met with Steven about target milestones for the year and project:

-   End of Winter Q - Proposal

    -   Tentative project idea:

        -   covering sex determination in hermaphroditic oysters

        -   chap 1: covering bioinfo/omics approaches to determining gene pathways and top marker genes relevant to sex determination in bivalves (spec. hermaphrodites and oysters). Identify pathways and relevant genes for sex determination in oysters.

        -   chap 2: relate these pathways to environmental factors and climate change. how are things like CO2, OA, and Temp altering the expression of key genes.

            -   potential wet work: qPCR of oysters weekly over the course of the season in diff. conditions

-   End of Spring Q - Committee Meeting

-   End of Spring Q - Chap. 1 Drafter
