project:
  type: website
  output-dir: docs/

website:
  title: "mewing-notebook"
  navbar:
    right:
      - about.qmd
      - icon: researchgate
        text: Researchgate
        href: https://www.researchgate.net/profile/Megan-M-Ewing
      - icon: github
        text: Github
        href: https://github.com/meganewing/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

