---
title: "June Daily Posts"
author: "Megan Ewing"
date: "06-05-2024"
categories: daily
format: 
  html:
    toc: true
editor: visual
---

### June 3rd/4th

Its hack-a-thon, but I've been terribly sick. My goals for hackathon were to 1. wrap up 541 lab, 2. finish the workflow for lurida, and 3. email potential committee members. When not resting I was able to do a little bit more work on the 3rd one, looking at committee requirements, potential folks to invite, and how to submit the milestone

### June 5th

Emailed committee members, heard back from 2/3. Luke and Jose on board, just waiting to hear back from Mac and then I'll send out the docusign form and submit the safs milestone.

Also worked on finalizing my manila clam repo, getting the readme docs updated. Forwarded the hisat workflow write up and repo to mac as well.

Troubleshooted VPN problems to no avail. And still sick so wasn't able to go into the office...

### June 6th

Heard back from mac and we're good to go. Finalized manila clam repo and finished updating the readme docs. Submitted final lab assignment.

### June 10th

Went over lurida workflow to date ( just blast) to check outputs and added some visualizations. Started to search for various known (to literature) genes associated with repro (ex. dmrt) to see if present in blast output. Coordinated with mac to setup a time to go over committee and clam stuff.
