---
title: "October Daily Posts"
author: "Megan Ewing"
date: "10-10-2024"
categories: daily
format: 
  html:
    toc: true
editor: visual
---

Whoops haven't updated daily posts in awhile... here's what you missed in the last 3 weeks:

-   submitted aquaculture 2025 abstract

-   had first committee meeting

-   met with individuals from NOAA, WDFW, King County, UW (both admin and profs), WSP and FHL to discuss career paths and opportunities to look out for

-   GRFP workshop mentoring!

-   got obscenely sick for a few days

Okay, here's where we are now:

### October 9th

Added some of my DEG findings and methods to a comparison chart with Giles' outputs to see if our results are consistent. Once we can confirm everything looks good, I can full deep dive with the interpretation of the results.

Last session of the GRFP workshop with the NSF style review. Really cool to see how diverse the applications are!

### October 11th 

Met with mac to review the results. Seems like there are differences in Giles' findings with STAR alignment rates and my HiSAT alignment rates. He trimmed before aligning (I did not), so next step is to go back and trim and re align one sample with hisat to see if it improves alignment rate. If it doesn't, then we'll use the feature counts matrix that was generated from STAR alignmened samples to run downstream analysis from there. If it does, then I'll trim all the samples, re-align them with hisat, and then do the downstream analyis.

This will have to wait until next week though because the Col. of Env. travel fund application is due today, and not the 18th as I originally thought.

### October 16th

Re writing the analysis as mentioned on Friday. Haven't run it yet as I'll need to go onto campus to get access to raven and my raw data files again without just re downloading it all.

Starting to think about chapter 1 methods. Found the paper Luke talked about in my committee meeting: "T[he genetic basis of novel trait gain in walking fish](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10592820/)"
