---
title: "May Daily Posts"
author: "Megan Ewing"
date: "05-21-2024"
categories: daily
format: 
  html:
    toc: true
editor: visual
---

Whoops forgot to do dailys for the first half (ok, three quarters) of the month, so here's weeklys:

### May 1-4

May 9th is my assigned day to lead 541, so on top of normal class and homework stuff, I was working on gathering curriculum material

### May 5-11

More curriculum prep stuff, regular class things, and caught up on lab homework (DESeq2 w featurecounts, blast, joining, gene enrichment, etc). Also open house is next weekend so did some prep with Andy for that.

### May 12-18

Class and regularly scheduled programming. Prep for open house, with grace. Went out on a boat (admiral jack!) with Rosalind and Maritime HS. And had the open house which was sick and had over 1200 estimated visitors!

### May 19-26

Class and lab, re installed x tools to finally get my notebook updated. Started previewing some literature to understand enriched biological processes for clam samples. Was out Thursday afternoon through Monday.

### May 27th

Was out of office still, but in the evening continued working on looking at enriched biological processes functions / role in various pathways.

### May 28th

Presentation for 541. Working on going back to the list of DEG and log2fold change to try and tie back the biological processes to try and parse which ones are increasing or decreasing with my samples. Lottttt of debugging and contemplating becoming an off-the-grid nomad so I never have to touch a computer again.

### May 29th

Bright and early I went to continue debugging, with little success. Moved on and wrote up the methods for the clam OA stuff from class/lab, refined my figures a bit, and made my presentation for the creative project for class.

### May 30

Wrote up speaker notes for my presenation, did some more background literature reading, and prepped a bit for the presentation. Had class (didn't present) and lab meeting. Found out during lab meeting that the issues I was having with figuring out how to connect DEG, log2fold change, and BP together was really close to the right solution. Steven says that DAVID provides a uniprot accession number associated with each GO term it gives you, and can use that to connect REVIGO output to DEG expression levels.
