---
title: "Clam Trials"
author: "Megan Ewing"
date: "03-17-2026"
categories: daily, projects
format: 
  html:
    toc: true
editor: visual
---

Preliminary trials to determine what temp manila seed can take for **repeated** acute thermal challenge

### Repeat Challenges

#### **36C - Exposure 1**

4/1/26

Seed were held in 12C, 20ppt prior to elevated temp exposure

Water temp measured with glass thermometer

Water temp was set to 36C using a water bath (glass beaker with 20ppt for clams; surrounding bath was DI water)

Clams (n=15) were placed in 36C for 2 hrs

***Observations***

-   actual water temp upon removal from incubator: 35.5C

-   Upon removal from incubator (prior to transfer to recovery): 5/15 had open shells with siphons or feet extended, 7/15 had slightly open shells (only mantle visible), 3/6 had closed shells.

-   Immediately following transfer to recovery: 15/15 closed shells

-   5 min following transfer to recovery: 15/15 closed shells

-   20 min following transfer to recovery: 12/15 slightly open shells or open with siphon/foot extended. 3/15 closed

-   18 hr: 15/15 closed shells

-   24 hr: 7/15 had closed shell, 8/15 had open shells with only siphons extended - responsive to dissection probe contact

-   48 hr: 1/15 had a closed shell. 14/15 had open shells with siphons extended and responsive to touch

#### **34C - Exposure 1**

4/6/26

Seed were held in 12C, 20ppt prior to elevated temp exposure

Water temp measured with glass thermometer

Water temp was set to 34C using a water bath (glass beaker with 20ppt for clams; surrounding bath was DI water)

Clams (n=15) were placed in 34C for 2 hrs

***Observations***

-   actual water temp upon removal from incubator: 33.5C

-   Upon removal from incubator (prior to transfer to recovery): 15/15 had closed shells

-   Immediately following transfer to recovery: 15/15 closed shells

-   5 min following transfer to recovery: 15/15 closed shells

-   20 min following transfer to recovery: 10/15 closed shells. 5/15 open shells with feet extended and siphons visible - all responded to contact with dissection probe

-   18 hr:

-   24 hr: 15/15 open with siphons extended & responsive to contact w/dissection probe

-   48 hr:

------------------------------------------------------------------------

**Preliminary trials to determine what temp manila seed can take for acute priming.**

### Trial 1

3/17 tested \~30C, \~36C, \~40C with n=6-7 clams each for 2 hours

Seed were held in 12C, 20ppt prior to elevated temp exposure

Water temps measured with infared thermometer

Clams were placed in plastic cups (1 per treatment) with 12C for recovery after exposure

**Observations:**

#### 30.2C

*30C (n=6)*

-   actual water temp upon removal from incubator: 30.2C

-   Upon removal from incubator (prior to transfer to recovery): 3/6 had slightly opened shells. 3/6 had closed shells

-   Immediately following transfer to recovery: 6/6 closed shells

-   5 min following transfer to recovery: 5/6 feet and siphons partially extended, shells slightly open and moving occasionally. 1/6 closed

-   20 min following transfer to recovery: 6/6 feet and siphons partially extended, shells slightly open and moving occasionally

-   90 min following transfer to recovery: 6/6 feet and siphons partially extended, shells slightly open, some occasional movement. Responds to contact w dissection probe along mantle (closing shell, retracting foot or siphon)

-   18 hr: 3/6 slightly open shells with siphons out and responsive to contact with dissection probe. 3/6 shells closed

-   24 hr: all slightly open and responsive

-   48 hr: all slightly open and responsive

```{=html}
<div style="text-align:center;">
  <iframe width="315" height="560"
  src="https://youtube.com/embed/4a9hVH0ZsNA?si=Jyv2GKeWxZzhR5IG"
  frameborder="0"
  allowfullscreen></iframe>
</div>
```

#### 33.4C

*36C (n=6)*

-   actual water temp upon removal from incubator: 33.4C

-   Upon removal from incubator (prior to transfer to recovery): 3/6 had slightly opened shells. 3/6 had closed shells

-   Immediately following transfer to recovery: 6/6 closed shells

-   5 min following transfer to recovery: 6/6 feet and siphons partially extended and moving occasionally, shells slightly open

-   20 min following transfer to recovery: 6/6 feet and siphons partially extended and moving occasionally, shells slightly open

-   90 min following transfer to recovery: 6/6 feet and siphons partially extended, shells slightly open, some occasional movement. Responds to contact w dissection probe along mantle (closing shell, retracting foot or siphon)

-   18 hr: 5/6 slightly open shells with siphons out and responsive to contact with dissection probe. 1/6 shells closed

-   24 hr: all slightly open and responsive

-   48 hr: all slightly open and responsive

```{=html}
<div style="text-align:center;">
  <iframe width="315" height="560"
  src="https://youtube.com/embed/H9a35rwwnkM?si=NfMvhyQlPHBeUBf4"
  frameborder="0"
  allowfullscreen></iframe>
</div>
```

#### 40.9C

*42C (n=7)*

-   actual water temp upon removal from incubator: 40.9C

-   Upon removal from incubator (prior to transfer to recovery): 6/6 had slightly opened shells with feet and siphons partially extruded

-   Immediately following transfer to recovery: 6/6 had slightly opened shells with feet and siphons partially extruded, no change from before. When prodded with dissecting probe, no response from any individuals. Indicates 100% mortality

-   5 min following transfer to recovery: same as previous

-   20 min following transfer to recovery: same as previous

-   90 min following transfer to recovery: same as previous. No response to contact w dissection probe along mantle, feet, or siphon

-   18 hr: same as previous / no change

-   24 hr: same as previous / no change

-   48 hr: same as previous / no change

```{=html}
<div style="text-align:center;">
  <iframe width="315" height="560"
  src="https://youtube.com/embed/iH2C4wkNAT0?si=09pc6QbFrB2VIagV"
  frameborder="0"
  allowfullscreen></iframe>
</div>
```

### Trial 2

#### 34.5C

36C target temp. 2 hr exposure then moved to 12C for recovery.

-   actual water temp upon removal from incubator: 34.5C

-   Upon removal from incubator (prior to transfer to recovery): 2/6 had slightly opened shells with siphons out. 2/6 had closed shells

-   Immediately following transfer to recovery: 6/6 closed shells

-   5 min following transfer to recovery: 6/6 feet closed shells

-   20 min following transfer to recovery: 6/6 feet and siphons partially extended and moving occasionally, shells slightly open and responds to contact w dissection probe along mantle (closing shell, retracting foot or siphon)

-   18 hr: 6/6 closed shells

-   24 hr: all slightly open and responsive

-   48 hr: 4/6 open and responsive, 2/6 tightly closed

#### 37.1C

38C target temp. 2 hr exposure then moved to 12C for recovery.

-   actual water temp upon removal from incubator: 37.1C

-   Upon removal from incubator (prior to transfer to recovery): 3/6 had slightly opened shells with siphons out. 3/6 had closed shells

-   Immediately following transfer to recovery: 2/6 open with foot + siphon out, and non responsive to dissection probe contact. 4/6 closed

-   5 min following transfer to recovery: 2/6 feet open and non responsive. 4/6 closed shells

-   20 min following transfer to recovery: 5/6 feet and siphons partially extended and moving occasionally, shells slightly open and responds to contact w dissection probe along mantle (closing shell, retracting foot or siphon). 1/6 closed

-   18 hr: 6/6 closed shells

-   24 hr: 5/6 slightly open and responsive. 1/6 closed

-   48 hr: 6/6 open and responsive (shockingly!)
